from peewee.peewee import Model, CharField, DecimalField, BigIntegerField, SqliteDatabase
from pyModeS import adsb


db = SqliteDatabase("receptor.db")


class RawData():

    timestamp = None
    downlinkformat = None
    frame = None

    def __init__(self, raw):
        self.timestamp = raw["timestamp"]["integer"]
        self.downlinkformat = raw["downlinkformat"]
        self.frame = raw["frame"]

    def __cmp__(self, other):
        return self.timestamp.__cmp__(other.timestamp)

    def __repr__(self):
        return "RawData: [tt=%d, dl=%d, fm=%s]" % self.timestamp, self.downlinkformat, self.frame


class MessageBuffer():

    icao = ""
    dataId = []
    dataPositionEven = []
    dataPositionOdd = []
    dataVelocity = []

    def __init__(self, **kwargs):
        for k, v in kwargs.iteritems():
            setattr(self, k, v)

    def addRawData(self, rawData):
        type = adsb.typecode(rawData.frame[1:29])
        if type >= 1 and type <= 4:
            self.dataId.append(rawData)
            self.dataId.sort(reverse=True)
        elif type >= 9 and type <= 18:
            flag = adsb.oe_flag(rawData.frame[1:29])
            if flag == 0:
                self.dataPositionEven.append(rawData)
                self.dataPositionEven.sort(reverse=True)
            else:
                self.dataPositionOdd.append(rawData)
                self.dataPositionOdd.sort(reverse=True)
        elif type == 19:
            self.dataVelocity.append(rawData)
            self.dataVelocity.sort(reverse=True)

    def isComplete(self):
        return self.dataId and self.dataPositionEven and self.dataPositionOdd and self.dataVelocity

    def __repr__(self):
        return "MsgBuff: [ic=%s, di=%d, do=%d, de=%d, dv=%d]" % (self.icao, len(self.dataId), len(self.dataPositionEven), len(self.dataPositionOdd), len(self.dataVelocity))


class ADSBInfo(Model):
    collector = CharField(max_length=64, null=True, default="")

    modeSCode = CharField(max_length=16, null=True, default="")
    callsign = CharField(max_length=16, null=True, default="")

    # Airplane position
    latitude = DecimalField(max_digits=40, decimal_places=20, default=0.0)
    longitude = DecimalField(max_digits=40, decimal_places=20, default=0.0)
    altitude = DecimalField(max_digits=40, decimal_places=20, default=0.0)

    # Airplane velocity
    verticalVelocity = DecimalField(max_digits=40, decimal_places=20, default=0.0)
    horizontalVelocity = DecimalField(max_digits=40, decimal_places=20, default=0.0)

    # Airplane angle
    groundTrackHeading = DecimalField(max_digits=40, decimal_places=20, default=0.0)

    # Observation date time generated by server
    timestamp = BigIntegerField(default=0)
    timestampSent = BigIntegerField(default=0)

    # Originals ADS-B messages
    messageDataId = CharField(max_length=100, default='')
    messageDataPositionEven = CharField(max_length=100, default='')
    messageDataPositionOdd = CharField(max_length=100, default='')
    messageDataVelocity = CharField(max_length=100, default='')

    class Meta:
        database= db


db.connect()
db.create_tables([ADSBInfo])